"""
Ctrl-Z FRC Team 4096
FIRST Robotics Competition 2018
Code for robot "Atla-Z"
contact@team4096.org
"""

import math

"""
Prepend these to any IDs.
DIO = Digital I/O
AIN = Analog Input
PWM = Pulse Width Modulation
CAN = Controller Area Network
PCM = Pneumatic Control Module
PDP = Power Distribution Panel
"""

### CONSTANTS ###

DEMO_MODE								= False
DEMO_MODE_DRIVETRAIN_SPEED_MULTIPLIER_Y	= 0.65
DEMO_MODE_DRIVETRAIN_SPEED_MULTIPLIER_R	= 0.65

# DRIVETRAIN #
PWM_DRIVE_MOTOR_LEFT_1					= 2
PWM_DRIVE_MOTOR_LEFT_2					= 3

PWM_DRIVE_MOTOR_RIGHT_1					= 0
PWM_DRIVE_MOTOR_RIGHT_2					= 1

# PATHFINDER #
DRIVE_MAX_SPEED							= 7
DRIVE_MAX_ACCEL							= 6
DRIVE_MAX_JERK							= 180
DRIVE_kP								= 0.15
DRIVE_kD								= 0

DRIVE_WHEELBASE_WIDTH					= 2.3
DRIVE_WHEEL_DIAMETER_INCHES				= 6.25

# ENCODERS #
DIO_DRIVE_ENC_LEFT_1					= 0
DIO_DRIVE_ENC_LEFT_2					= 1

DIO_DRIVE_ENC_RIGHT_1					= 2
DIO_DRIVE_ENC_RIGHT_2					= 3

DRIVE_ENCODER_LEFT_REVERSED				= True
DRIVE_ENCODER_RIGHT_REVERSED			= False

DRIVE_CORRECTION_ENABLED				= False

DRIVE_ENCODER_TICKS_PER_REV				= 256
DRIVE_TICKS_PER_FOOT					= 12 / (math.pi * DRIVE_WHEEL_DIAMETER_INCHES / DRIVE_ENCODER_TICKS_PER_REV)

DRIVE_CORRECTION_ROTATION_THRESHOLD		= 0.05
DRIVE_CORRECTION_PROPORTION_FORWARD		= 0.1
DRIVE_CORRECTION_PROPORTION_REVERSE		= 0.04
DRIVE_CORRECTION_PROPORTION_FORWARD_ENC	= 0.009
DRIVE_CORRECTION_PROPORTION_REVERSE_ENC	= 0.009

DRIVE_ROTATION_MULTIPLIER 				= 0.85

# Minimum power required.
DRIVE_MIN_ROTATION_OUTPUT_TANK			= 0.5
DRIVE_MIN_OUTPUT_TANK 					= 0.5

## PNEUMATICS ##
CAN_PCM 								= 2

PCM_DRIVE_SOLENOID_SHIFTER_1			= 0
PCM_DRIVE_SOLENOID_SHIFTER_2			= 7
ID_LOW_GEAR								= 0
ID_HIGH_GEAR							= 1

AIN_PRESSURE_SENSOR 					= 0

## ELEVATOR ##
CAN_ELEVATOR_TALON						= 1
CAN_ELEVATOR_VICTOR_SPX					= 3
PCM_ELEVATOR_BRAKE_SOLENOID_1			= 1
PCM_ELEVATOR_BRAKE_SOLENOID_2			= 6

ELEVATOR_MIN							= 0.25
ELEVATOR_TICKS_PER_FOOT					= 141000
ELEVATOR_SPEED_MULTIPLIER				= 0.6
ELEVATOR_LIMIT_SWITCH					= 4
ELEVATOR_POSITION_DICT					= [0, 0.25, 3, 6.40]

## INTAKE ##
PWM_MOTOR_INTAKE_LEFT					= 4
PWM_MOTOR_INTAKE_RIGHT					= 5
PWM_MOTOR_ROTATION						= 6
PCM_INTAKE_SOLENOID_1					= 2
PCM_INTAKE_SOLENOID_2					= 5
PDP_MOTOR_INTAKE						= 7

INTAKE_VEL_FORWARD						= 1.0
INTAKE_VEL_REVERSE						= -1.0
INTAKE_CURRENT_THRESHOLD				= 30

## CLIMBER ##
PWM_CLIMBER_MOTOR						= 7
PWM_CLIMBER_SERVO						= 9

SERVO_RELEASE_ANGLE						= 180

## MISC ##
DIO_PBOT_CHECK							= 9
